# encoding: utf-8

require "rubygems"
require "bundler/setup"

# Loads bundler tasks
Bundler::GemHelper.install_tasks

# Loads the Hexx::RSpec and its tasks
require "hexx-rspec"
Hexx::RSpec.install

# Sets the Hexx::RSpec :test task to default
task default: :test
