# encoding: utf-8

guard :rspec, cmd: "rake test" do

  watch(/^lib(.+)\.rb$/) do |m|
    "spec/tests#{ m[1] }_spec.rb"
  end

  watch("spec/tests/*_spec.rb")

  watch("lib/*.rb")            { "spec" }
  watch("spec/support/*.rb"    { "spec" }
  watch("spec/spec_helper.rb") { "spec" }

end
